### ISSUE TITLE
feature: bypass invidious

### ISSUE THREAD

**Issue by atomGit** [jankkm/invidioucious#2]
sometimes invidious fails to play a video without reason, such as a future scheduled video, etc., and in such cases i often go to the youtube site - it would be nice if one were able to do so without having to disable the extension

so if one is visiting an invidious instance and clicks the youtube link, it would load youtube instead of reloading invidious

**Comment by jankkm** [comment]
Yeah I thought about this before but it's not very easy to do. I will have another look though and if it's feasible I will probably add that feature.

**Comment by jankkm** [comment]
I just added the feature, wasn't too hard after all. The update to 0.9.5 is already in the store.

**Comment by atomGit** [comment]
mozilla really screwed up about:addons so maybe i'm missing something here, but i have .9.6.1 installed and i'm not seeing any menu from the toolbar icon to select the instance (R or L click)

**Comment by jankkm** [comment]
This issue is about the „Watch on YouTube“ link. Please check if this works for you now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by atomGit** [comment]
i see this has been implimented and seems to work great - thanks much!
