### ISSUE TITLE
doesn't load invidious instance

### ISSUE THREAD

**Issue by atomGit** [jankkm/invidioucious#3]
look at the last post [here](https://12bytes.org/16844/morning-news-bytes-25-jul-2019)

it's not replacing the youtube iframe with invidious - only when you select from the FF context menu, 'show only this frame', or similar, does the invidious instance load

i didn't have this problem with other invidious extensions

**Comment by jankkm** [comment]
I am aware of this, it has been reported to me before. Many extensions use an API that redirects only after accessing Youtube servers which also works on iframe but is bad for privacy. The webRequest API that I use changes the url before any request to the server but it only looks on the url in the address bar. This means that the iframe itself has to be changed in the website source code.
This is on my to do list and will be added as soon as I have time for it.

**Comment by jankkm** [comment]
It works on iframes as well now. Please let me know if it works alright for you.

Unfortunately proxy mode doesn't work in iframes yet (if you have that enabled in the settings) but I am trying to add that.

**Comment by atomGit** [comment]
still not working with 0.9.6.1 - just looking at uMatrix (i didn't look at the browser console), there is no request made to the invidious instance - there are (and were prior to 961) requests to youtube.com and if i allow the XHR, JS and frame, then the video will play from YT, but not the invidious instance - so the behavior is the same as previous; only if i load the frame in a new tab/window will invidious be used

**Comment by atomGit** [comment]
dunno if this would help or not, but you could look at the [Invidition](https://gitlab.com/Booteille/invidition) code maybe

**Comment by jankkm** [comment]
Could you please post the link that it doesn’t work on?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jankkm** [comment]
I think I know what the issue is. Please check if it works here: https://therightscoop.com/lindsey-graham-promises-a-deep-dive-after-ig-releases-report-on-russia-probe-video/

I will continue working on it on Monday.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by atomGit** [comment]
it does, yes

**Comment by atomGit** [comment]
> Could you please post the link that it doesn’t work on?

it appears to be working all the time at present - i think what may have happened in the invidious instance i was using choked, but i don't understand why i wasn't seeing an http request in uMatrix

i'll let it to you to close this since it seems you may have found a problem

**Comment by atomGit** [comment]
odd, it's not loading, nor making any requests to the invidious instance again

https://www.rt.com/news/465180-brazil-40million-gold-heist/

the above video won't load, so i switched instances and is still didn't load - i then disabled Invidioucious and enabled Invidition and the video loaded fine using the same invidious instance (invidious.13ad.de)

note that in neither case am i proxying the video and the auto-play stuff is disabled

**Comment by jankkm** [comment]
I just pushed a new version to the store which should work much better for embedded videos.

**Comment by atomGit** [comment]
am testing this ext. again, finally, and so far it seems to work fine, even with iframes - all is good
