### ISSUE TITLE
"Cookie" option interferes with video site settings

### ISSUE THREAD

**Issue by ghost** [jankkm/invidioucious#4]
Selecting said option on the setting pane, impede loading correctly the own settings of the video site, making effectively impossible to load basic features like signing in or interface language.

**Comment by jankkm** [comment]
Please check if disabling Proxy mode makes it work again and also please give me an example of a page that breaks.

**Comment by jankkm** [comment]
Oh I think I misunderstood before. Is this issue about logging into the invidious instance? That makes sense because the cookie header is completely overwritten by the extension. But why would you want to save settings both in the extension and in your account?

**Comment by ghost** [comment]
No, it is not abut logging to an invidious instance (although you can't do it if you use invidiouscious), it is about being unable to fully use an invidious site when the extension is enabled and the "Cookie" option checked (works well if unchecked).

Steps to reproduce:
- Disable this extension
- Create an account on invidio.us
- Set a language diferent from english for interface
- Same for subtitles
- Navigate to any video
- You will see the site using your settings

Now:
 - Enable this extension
 - Check the "Cookie" option
 - Set invidio.us as your desired instance for redirection
 - Do whatever you want with the other options
 - Navigate to any youtube video
 - You will be redirected to invidio.us but the site will be displayed in english.

Language isn't the only problem, any other setting is not used if you use the cookie and there is no way to manually configure these settings anywhere making invidioucious not truly usable on many scenarios.

This is of course because the cookie settings seem to be hardcoded, so I see three ways to approach this problem:

1. Make the cookie manually configurable
2. Use the settings from the invidio instance (preferable)
3. Clearly explain in the setting pane what "cookie" option will do, so people don't get confused.

**Comment by jankkm** [comment]
In short you cannot use a mix of settings from the extension and from your login. Why would you want that.
I could:
- add an option that disables all settings so the extension is only for redirection and you can use the settings set in your login (real cookie)
- add other settings like language to the extension so you don’t need your login.

Which would help you more?

I will add a few words to the settings page that there is no login possible if the extension sends its cookie information.

**Comment by ghost** [comment]
Both are great options, personally, I would find more useful the first one, to leave only redirection enabled. But the second one may be better for privacy, therefore other users may find it more valuable.

Whichever one you decide on would be a great improvement!

**Comment by eridanired123** [comment]
Both are great options, personally, I would find more useful the first one, to leave only redirection enabled. But the second one may be better for privacy, therefore other users may find it more valuable.

Whichever one you decide on would be a great improvement!

**Comment by jankkm** [comment]
I just uploaded a new version:
-you can set the language now
-cookie mode is explained a little better
