### ISSUE TITLE
"channel does not exist" error

### ISSUE THREAD

**Issue by atomGit** [jankkm/invidioucious#6]
load with invidioucious disabled:
https://www.youtube.com/user/TheProperPeople
then enable it and refresh the page

"channel does not exist"

**Comment by jankkm** [comment]
I am not able to reproduce this.
I am being redirected to https://invidious.enkirton.net/channel/TheProperPeople correctly.
This might be an issue with the invidious instance you are using.

**Comment by atomGit** [comment]
the instance doesn't matter, but i see what's happening - enable dark mode and try it again

i'm being forwarded to:
`https://invidio.us/channel/TheProperPeople&dark_mode=true&thin_mode=false&autoplay=false&continue=false&video_loop=false&listen=false&quality=dash&local=false`

whereas it should be:
`https://invidio.us/channel/TheProperPeople?dark_mode=true&thin_mode=false&autoplay=false&continue=false&video_loop=false&listen=false&quality=dash&local=false`

the first URL param is preceded by `&` instead of `?`

**Comment by atomGit** [comment]
hmmm, strange - i thought i had it working ok once i disabled dark mode, but then i added `?dark_mode=true` in the custom param box - this resulted in a warning that the param needs to be preceded by `&`, which is incorrect (since it's the 1st param) but i saved it and again i was forwarded to `https://invidio.us/channel/TheProperPeople&dark_mode=true& ...`

so then i removed `?dark_mode=true` and, with dark mode option also disabled, this should have restored proper function, but now i'm forwarded to `https://invidio.us/channel/TheProperPeople&dark_mode=false& ...` which again results in the unavailable error

when i first disabled the dark mode option, i thought (but not 100% sure) that all params were stripped, which would have led to...
`https://invidio.us/channel/TheProperPeople`
... as it apparently did in your own test, but now i can't get rid of the params anymore

even did a browser restart and no joy

**Comment by atomGit** [comment]
ok, what i had to do was uninstall the extension AND restart FF and reinstall and now it works again - so in short, i can't enable dark mode - i didn't test any other params

**Comment by jankkm** [comment]
Do you have a reason to not use the cookie mode? Should all work fine with that. I will look into the issue with the parameters though and it should be an easy fix.

**Comment by jankkm** [comment]
By the way: the custom parameter is always added at the end which is why it has to be preceded by an ampersand.

**Comment by atomGit** [comment]
> Do you have a reason to not use the cookie mode? 

not particularly - i'm a privacy freak and i worry about a malicious instance i suppose, but i'll give that a shot

> the custom parameter is always added at the end which is why it has to be preceded by an ampersand

negative - pretty sure the first param must be preceded by a `?` and all those following by `&` ... at least that's always the way i see it done in a URL, possibly because `&` can be a legitimate element in a URL so there needs to be something to separate the URL and params

just note that there's 2 bugs here - the first param being preceded by `&` and the params not being cleared when all options (and custom params) are disabled

**Comment by atomGit** [comment]
oh, i see no cookie is actually stored in the preferences - great - and yeah, the cookie mode work fine

**Comment by jankkm** [comment]
I was able to check the code and the main problem is that block of arguments is not preceded by a ? but by a & which works for videos (which is why I didn't see the bug before) but not on channels. Thanks for finding that bug.

The second bug you mention is not really one because the extension sets the disabled values to false by design which generally works fine. I will probably change that though.

You tried to add the dark_mode argument as a custom one which adds it to the end. This way it is BOTH the first and the last argument. So it is actually correct that the custom argument has to start with an &.

**Comment by jankkm** [comment]
It should work fine now.

**Comment by atomGit** [comment]
the "channel does not exist" error is fixed, but the param problem still exists - i'll open a new issue for that
